### ISSUE TITLE
C-PageUp jumps 2 tabs

### ISSUE THREAD

**Issue by Massimo-B** [Pale-Moon-Addons-Team/pentadactyl-pm-legacy#4]
CTRL+PageUp or PageDown jumps 2 tabs instead of 1.

I tried defining this in my .pentadactylrc:

`:nmap <C-PageDown> <Pass><C-PageDown>`
That makes it jump 3 tabs.

`:nmap <C-PageUp> <Pass><C-PageUp>`
Same, jumps 2 tabs.

**Comment by wolfbeast** [comment]
Please direct any current and future issues to https://github.com/madand/pentadactyl-pm

This repo is no longer maintained.
